//
// ModelCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ModelCharacter: Codable {

    public var id: Int?
    public var name: String?
    public var status: String?
    public var gender: String?
    public var image: String?

    public init(id: Int?, name: String?, status: String?, gender: String?, image: String?) {
        self.id = id
        self.name = name
        self.status = status
        self.gender = gender
        self.image = image
    }


}

