//
// LocationsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct LocationsList: Codable {

    public var info: Info?
    public var results: [Location]?

    public init(info: Info?, results: [Location]?) {
        self.info = info
        self.results = results
    }


}

