//
// CharactersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class CharactersAPI {
    /**
     Characters List
     
     - parameter page: (query) number of page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func charactersGet(page: Int? = nil, completion: @escaping ((_ data: CharactersList?,_ error: Error?) -> Void)) {
        charactersGetWithRequestBuilder(page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Characters List
     - GET /character/
     - parameter page: (query) number of page (optional)
     - returns: RequestBuilder<CharactersList> 
     */
    open class func charactersGetWithRequestBuilder(page: Int? = nil) -> RequestBuilder<CharactersList> {
        let path = "/character/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<CharactersList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
